### ISSUE TITLE
Link to issue tracker

### ISSUE THREAD

**Issue by chrysn** [ace-wg/ace-edhoc-oscore-profile#6]
Please consider adding a pointer to the repository to the document (and, in coordination with chairs, [to the data tracker](https://datatracker.ietf.org/doc/draft-ietf-ace-edhoc-oscore-profile/)).

The one in the document can easily be done in the latest markdown format by adding to the file's header:

```yaml
venue:
  group: Authentication and Authorization for Constrained Environments (ace) 
  mail: ace@ietf.org
  github: ace-wg/ace-edhoc-oscore-profile
```
